# Generated by Django 4.1.6 on 2023-02-07 22:16

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_name',
            field=models.ImageField(upload_to=product.models.Product.get_file_path),
        ),
    ]
